# Generated by Django 3.2.25 on 2024-12-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['shop', 'name'], name='pharmacy_ap_shop_id_a88d0b_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['stock'], name='pharmacy_ap_stock_ee44ae_idx'),
        ),
    ]
